const byId = id => document.getElementById(id);

export const EL = {
  canvas: byId('gameCanvas'),
  canvasWrap: byId('canvas-wrap'),
  hud: byId('hud'),
  startOv: byId('start-overlay'),
  appVersion: byId('app-version'),
  goOv: byId('go-overlay'),
  cdWrap: byId('cd-wrap'),
  cdNum: byId('cd-num'),
  modesGrid: byId('modes-grid'),
  skinsGrid: byId('skins-grid'),
  homeModal: byId('home-modal'),
  homeModalTitle: byId('home-modal-title'),
  homeModalClose: byId('home-modal-close'),
  homeHowBtn: byId('home-how-btn'),
  homeStatsBtn: byId('home-stats-btn'),
  homeAchievementsBtn: byId('home-achievements-btn'),
  homeSettingsBtn: byId('home-settings-btn'),
  homeHowPanel: byId('home-how-panel'),
  homeStatsPanel: byId('home-stats-panel'),
  homeAchievementsPanel: byId('home-achievements-panel'),
  homeSettingsPanel: byId('home-settings-panel'),
  achievementsSummary: byId('achievements-summary'),
  achievementsList: byId('achievements-list'),
  controlModeGroup: byId('control-mode-group'),
  mobileControls: byId('mobile-controls'),
  statsGrid: byId('stats-grid'),
  startBtn: byId('start-btn'),
  restartBtn: byId('restart-btn'),
  homeBtn: byId('home-btn'),
  hSpeedLabel: byId('h-speed-label'),
  hScore: byId('h-score'),
  hMult: byId('h-mult'),
  hDist: byId('h-dist'),
  hSpeed: byId('h-speed'),
  hBest: byId('h-best'),
  hBestdist: byId('h-bestdist'),
  goModeLabel: byId('go-mode-label'),
  goScore: byId('go-score'),
  goAchievements: byId('go-achievements'),
  goAchievementsList: byId('go-achievements-list'),
  goBest: byId('go-best'),
  goBestHeader: byId('go-best-header'),
  goDist: byId('go-dist'),
  goBestdist: byId('go-bestdist'),
  goMult: byId('go-mult'),
};

export const ctx = EL.canvas.getContext('2d');
